name: Cypress Tests

on:
  push:
    branches: [master]
  workflow_dispatch:
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      # if some of matrix job failes, other will continue to run, if we set true, all matrix jobs will be canceled if one of them failed.
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run sauceLab
