name: Cypress Tests

on:
  push:
    branches: [main]
  workflow_dispatch:
    
jobs:
  cypress-test:
    runs-on: ubuntu-latest
    
    strategy:
      # if some of matrix job failes, other will continue to run, if we set true, all matrix jobs will be canceled if one of them failed.
      fail-fast: false
      matrix:
        containers: [0,1]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: cypress-io/github-action@v6
        with:
          start: npm run sauceLab

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Reports-data
          path: cypress/reports/html
          retention-days: 30
