name: Cypress Tests

on:
  push:
    branches: [main]
  workflow_dispatch:
    
jobs:
  cypress-test:
    runs-on: ubuntu-latest
    
    strategy:
      # if some of matrix job failes, other will continue to run, if we set true, all matrix jobs will be canceled if one of them failed.
      fail-fast: false
      matrix:
        containers: [0,1]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install packages
        run: npm install
      - run: npx cypress run
          
     
        #uses: cypress-io/github-action@v6
        #with:
          #start: npm run sauceLab
